apiVersion: v1  
kind: Pod
metadata:
  name: dpdk-ovs
  labels:
    app: first-test
  namespace: dpdk
  annotations:
    cpu-manager-specify-cpus: "1,4,6,8,10"
spec:
#  nodeSelector:  
#    kubernetes.io/hostname: vm1
  shareProcessNamespace: true
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: ovs
#    image: 192.168.10.150:30500/testpmd:latest
    image: ovs:v2
    resources:  
      limits:  
        cpu: "5"
        hugepages-1Gi: 1Gi  
        memory: "4Gi" 
      requests:
        cpu: "5"  
        hugepages-1Gi: 1Gi 
        memory: "4Gi" 
    command: ["python3", "/etc/scripts/ovs.py"] 
    securityContext:  
      privileged: true
      capabilities:
        add: ["SYS_ADMIN", "SYS_PTRACE"]
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:  
    - name: hugepages
      mountPath: /dev/hugepages  
    - name: local
      mountPath: /usr/local
    - name: scripts
      mountPath: /etc/scripts
    - name: logs
      mountPath: /var/log
    env:  
    - name: KUBERNETES_EXCLUSIVE_CPUS  
      valueFrom:  
        fieldRef:  
          fieldPath: metadata.annotations['cpu-exclusive-cpusalloc']
  volumes:
  - name: hugepages  
    hostPath:  
      path: /dev/hugepages  
  - name: local
    hostPath:  
      path: /usr/local
  - name: scripts
    hostPath:
      path: /home/kagami/scripts
  - name: logs
    hostPath:
      path: /var/log/dpdktest