apiVersion: v1  
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: dpdk
spec: 
  nodeSelector:  
    kubernetes.io/hostname: kubemaster
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: registry
    image: registry.aliyuncs.com/google_containers/registry:latest 
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: registry-storage
      mountPath: /var/lib/registry  
    env:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: "true"
  volumes:  
  - name: registry-storage  
    hostPath:  
      path: /data/registry  
      type: DirectoryOrCreate
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: registry  
  namespace: dpdk  
spec:  
  type: NodePort  
  ports:  
  - port: 5000  
    targetPort: 5000  
    nodePort: 30500  
  selector:  
    app: registry