apiVersion: v1  
kind: Pod
metadata:
  name: test
  labels:
    app: first-test
  namespace: dpdk
  annotations:
    cpu-manager-hpcCoreSelect-policy: "PreferHighPerf" # or StrictHighPerf or AvoidHighPerf
    cpu-manager-smtCoreSelect-policy: "Packed"         # or Distributed
spec:  
#  nodeSelector:  
#    kubernetes.io/hostname: vm1
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: ubuntu
#    image: 192.168.10.150:30500/testpmd:latest
    image: ubuntu:24.04
    resources:  
      limits:  
        cpu: "13" 
        memory: "1Gi" 
      requests:
        cpu: "13"  
        memory: "1Gi" 
    command: ["sleep", "infinity"] 
    securityContext:  
      privileged: true
    env:  
    - name: KUBERNETES_EXCLUSIVE_CPUS  
      valueFrom:  
        fieldRef:  
          fieldPath: metadata.annotations['cpu-exclusive-cpusalloc']